"""Embedded defaults for the unified STEP-ROM pipeline.

JSON configuration files were intentionally removed; these dictionaries are
cloned by the orchestrator and adjusted from user input at runtime.
"""

from __future__ import annotations

from copy import deepcopy
from typing import Any

EXPORT_DEFAULTS: dict[str, Any] = {'design_point_name': '0',
 'default_unit': 'mm',
 'base_system_name': 'SYS',
 'input_archive_name': 'auto',
 'project_file_name': 'auto',
 'write_updated_archive': True,
 'updated_archive_name': 'auto',
 'parameters': [{'name': 'P4', 'value': 2},
                {'name': 'P5', 'value': 10},
                {'name': 'P6', 'value': 15},
                {'name': 'P7', 'value': 15}],
 'bc_count': 1,
 'case_prefix': 'bc',
 'modal_start_sys': 1,
 'step_lsdyna_start_sys': 2,
 'real_lsdyna_start_sys': 3,
 'sys_step': 3,
 'modal_file_patterns': ['mode*_step.txt', 'modal_reference_info.txt']}

GENERATE_K_DEFAULTS: dict[str, Any] = {'exports_root': 'exports',
 'case_glob': 'bc_*',
 'base_key_name': 'model.key',
 'modal_dir_name': 'modal',
 'step_dir_name': 'step',
 'selected_modes': [1, 2, 3],
 'model_family': 'auto',
 'generate_linear_and_nonlinear_decks': True,
 'output_suffix': '_nl.k',
 'output_suffix_nl': '_nl.k',
 'output_suffix_lin': '_lin.k',
 'patch_implicit_cards': True,
 'patch_step_disable_element_erosion': True,
 'patch_step_control_timestep_erode_value': 0,
 'step_load_scheme': 'prescribed_motion_step',
 'step_control_basis': 'q',
 'step_expected_reaction_source': 'bndout',
 'step_requires_fitted_fe_q': False,
 'primary_step_prescribed_mode': 'translational',
 'prescribed_dofs': ['UX', 'UY', 'UZ'],
 'projection_dofs': ['UX', 'UY', 'UZ'],
 'force_normal_axis': None,
 'strict_solid_normal_step_guard': True,
 'allow_low_normal_content_modes': True,
 'min_normal_content_ratio_for_selected_modes': 1e-10,
 'solid_step_prescription_scope': 'all_free_nodes',
 'solid_prescribe_midside_nodes': True,
 'solid_fail_if_no_surface_nodes': False,
 'zero_tol': 1e-18,
 'curve_id': 900001,
 'end_time': 1.0,
 'solid_q_scale_basis': 'min_edge',
 'solid_q_over_min_edge_sweep': [1e-08, 3e-08, 1e-07],
 'use_full_q_sweep_for_prescribed_step': True,
 'single_q_values': 'auto',
 'pair_q_values': 'auto',
 'triple_q_values': 'auto',
 'combined_step_q_scaling': 'active_count',
 'include_single_q_values_for_all_interaction_q': True,
 'dual_q_factor': 1.0,
 'generate_dual_mode_decks': False,
 'dual_p_value': 'auto',
 'dual_output_suffix': '.k',
 'dual_prescribed_mode': 'normal_only',
 'dual_prescribed_dofs': None,
 'exclude_node_set_ids': [],
 'exclude_all_set_node_lists': False,
 'auto_exclude_spc_nodes': True,
 'auto_exclude_spc_sets': True,
 'auto_exclude_spc_node_cards': True,
 'report_excluded_nodes': True,
 'enable_solid_step_preflight': True,
 'preflight_allow_auto_shrink': True,
 'preflight_shrink_factor': 0.5,
 'preflight_max_shrink_steps': 12,
 'preflight_reject_on_bad_geometry': True,
 'preflight_max_disp_over_thickness': 0.001,
 'preflight_max_motion_over_min_edge': 0.001,
 'preflight_min_tet_volume_ratio': 0.99,
 'preflight_max_sample_elements': 200000,
 'write_step_manifest': True,
 'step_manifest_filename': 'step_manifest.json',
 'nonlinear_implicit_general': {'imflag': 1,
                                'dt0': 0.0,
                                'imform': 2,
                                'nsbs': 10,
                                'igs': 2,
                                'cnstn': 0,
                                'form': 0,
                                'zero_v': 0},
 'linear_implicit_general': {'imflag': 1,
                             'dt0': 0.0,
                             'imform': 2,
                             'nsbs': 10,
                             'igs': 2,
                             'cnstn': 0,
                             'form': 0,
                             'zero_v': 0},
 'nonlinear_implicit_solution': {'nsolvr': 12,
                                 'ilimit': 200,
                                 'maxref': 50,
                                 'dctol': 0.001,
                                 'ectol': 0.01,
                                 'rctol': 0.001,
                                 'lstol': 0.9,
                                 'abstol': 1e-20,
                                 'dnorm': 2,
                                 'diverg': 1,
                                 'istif': 1,
                                 'nlprint': 1,
                                 'nlnorm': 2,
                                 'd3itctl': 0,
                                 'cpchk': 0,
                                 'arcctl': 0,
                                 'arcdir': 0,
                                 'arclen': 0.0,
                                 'arcmth': 0,
                                 'arcdmp': 0.0,
                                 'arcpsi': 0.0,
                                 'arcalf': 0.0,
                                 'arctim': 0.0,
                                 'lsmtd': 4,
                                 'lsdir': 2,
                                 'irad': 0,
                                 'srad': 0.0,
                                 'awgt': 0.0,
                                 'sred': 0.0,
                                 'kssize': 0},
 'linear_implicit_solution': {'nsolvr': 12,
                              'ilimit': 200,
                              'maxref': 50,
                              'dctol': 0.001,
                              'ectol': 0.01,
                              'rctol': 0.001,
                              'lstol': 0.9,
                              'abstol': 1e-20,
                              'dnorm': 2,
                              'diverg': 1,
                              'istif': 1,
                              'nlprint': 1,
                              'nlnorm': 2,
                              'd3itctl': 0,
                              'cpchk': 0,
                              'arcctl': 0,
                              'arcdir': 0,
                              'arclen': 0.0,
                              'arcmth': 0,
                              'arcdmp': 0.0,
                              'arcpsi': 0.0,
                              'arcalf': 0.0,
                              'arctim': 0.0,
                              'lsmtd': 4,
                              'lsdir': 2,
                              'irad': 0,
                              'srad': 0.0,
                              'awgt': 0.0,
                              'sred': 0.0,
                              'kssize': 0}}

LSDYNA_DEFAULTS: dict[str, Any] = {'exports_root': 'exports',
 'bc_count': 1,
 'bc_name_pattern': 'bc_{index:02d}',
 'step_subdir_name': 'step',
 'file_glob': '*.k',
 'organize_mode': 'copy',
 'job_root_name': 'jobs',
 'overwrite_job_dirs': True,
 'max_parallel': 1,
 'timeout_sec': None,
 'solver_exe': 'F:\\\\Program Files\\\\ANSYS '
               'Inc\\\\v242\\\\ansys\\\\bin\\\\winx64\\\\lsdyna_dp.exe',
 'solver_args': ['i={kfile_name}', 'ncpu=2', 'memory=20m'],
 'launch_via_bat': True,
 'run_bat_name': 'run_job.bat',
 'bat_pause_on_error': False,
 'working_dir_mode': 'job_dir',
 'log_stdout_name': 'solver_stdout.txt',
 'log_stderr_name': 'solver_stderr.txt',
 'manifest_name': 'job_manifest.json',
 'only_organize': False,
 'only_run_existing_jobs': False,
 'export_reactions': True,
 'reactions_dir_name': 'reactions',
 'reaction_source_file': 'bndout',
 'reaction_filename_pattern': '{jobname}.txt',
 'overwrite_reaction_files': True,
 'write_reactions_manifest': True,
 'dual_job_prefix': 'dual_mode',
 'dual_results_dir_name': 'dual_fields',
 'dual_export_patterns': ['d3plot*', 'd3dump*', 'binout', 'bndout', 'nodout', 'glstat'],
 'write_dual_manifest': True,
 'process_real_load_key': True,
 'real_load_filename': 'real_load.key',
 'copy_real_load_key_instead_of_move': True,
 'real_job_root_name': 'real_jobs',
 'fe_reference_dir_name': 'fe_reference',
 'fe_export_patterns': ['d3plot*',
                        'd3dump*',
                        'binout',
                        'bndout',
                        'nodout',
                        'glstat',
                        'matsum',
                        'rcforc',
                        'spcforc',
                        'ncforc'],
 'write_fe_manifest': True,
 'overwrite_export_payload': True}

ROM_DEFAULTS: dict[str, Any] = {'exports_root': 'exports',
 'bc_count': 1,
 'bc_name_pattern': 'bc_{index:02d}',
 'modal_dir_name': 'modal',
 'reactions_dir_name': 'reactions',
 'dual_results_dir_name': 'dual_fields',
 'fe_reference_dir_name': 'fe_reference',
 'fe_reference_job_name': 'real_load',
 'rom_dir_name': 'rom',
 'selected_modes': [1, 2, 3],
 'reaction_sign': 1.0,
 'use_rotations_in_generalized_force': True,
 'fe_generalized_force_source': 'auto',
 'use_dual_modes': False,
 'dual_p_value': 1.0,
 'dual_job_prefix': 'dual_mode',
 'd3plot_filename': 'd3plot',
 'd3plot_backend': 'auto',
 'd3plot_state_index': -1,
 'dual_zero_normal_dof': True,
 'compare_with_fe': True,
 'normal_dof': 'auto',
 'auto_normal_prefer': 'modal',
 'auto_normal_flat_ratio_max': 0.08,
 'geometry_normal_axis': None,
 'auto_normal_reference_modes': [1, 2, 3],
 'step_dir_name': 'step',
 'step_manifest_filename': 'step_manifest.json',
 'thickness': 'auto',
 'thickness_fallback': 1.0,
 'fe_projection_dofs': ['UX', 'UY', 'UZ'],
 'w_measure': 'wmax_over_h',
 'fe_q_fit_space': 'primary_normal',
 'fe_projection_error_threshold': 1.0,
 'fe_load_factor_from_time': True,
 'newton_max_iter': 80,
 'newton_tol': 1e-10,
 'fd_eps': 1e-07,
 'plot_title': 'ROM vs FE',
 'plot_filename': 'rom_vs_fe.png',
 'curve_csv_filename': 'rom_vs_fe.csv',
 'coefficients_json_filename': 'rom_canonical_step_coefficients.json',
 'step_summary_csv_filename': 'step_canonical_summary.csv',
 'report_filename': 'step_report.txt',
 'fe_plot_title': 'FE nonlinear static displacement curve',
 'fe_plot_filename': 'fe_static_curve.png',
 'rom_plot_title': 'STEP ROM static displacement curve',
 'rom_plot_filename': 'rom_static_curve.png',
 'd3plot_reference_state': 'first',
 'fe_generalized_force_sources': ['bndout', 'spcforc', 'ncforc', 'rcforc', 'projected_equilibrium'],
 'validate_external_force_path': True,
 'force_path_min_abs_norm': 1e-30,
 'force_path_min_relative_norm': 1e-08}

def pipeline_defaults() -> dict[str, dict[str, Any]]:
    """Return isolated mutable defaults for every pipeline stage."""
    return {
        "export": deepcopy(EXPORT_DEFAULTS),
        "generate_k": deepcopy(GENERATE_K_DEFAULTS),
        "lsdyna": deepcopy(LSDYNA_DEFAULTS),
        "rom": deepcopy(ROM_DEFAULTS),
    }
